language: rust

rust:
    - stable
    - nightly

os:
    - linux

script:
    - cargo build --verbose
    - cargo build --no-default-features
    - cargo test --verbose
    - cargo test --features="serde_serialization" --verbose
    - cargo doc --verbose
