[package]
name = "sampler"
version = "0.1.0"
authors = ["mitchmindtree <mitchell.nordine@gmail.com>"]

[features]
default = ["wav"]
wav = ["hound"]

[dependencies]
instrument = { path = "../instrument" }
pitch_calc = "0.10.0"
sample = "0.3.0"
time_calc = "0.10.1"

# optional dependencies
hound = { optional = true, version = "1.1.0" }

[dev-dependencies]
find_folder = "0.3.0"
portaudio = "0.6.2"
